# Generated by Django 3.1.7 on 2021-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_finish',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time_start',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
