# Generated by Django 3.1.6 on 2021-02-17 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='slug')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='holiday_date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.country')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_from', models.DateField(verbose_name='event_start_date')),
                ('start_time', models.TimeField(verbose_name='event starts...')),
                ('date_till', models.DateField(verbose_name='event_end_date')),
                ('end_time', models.DateTimeField(verbose_name='event_end_time...')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
